### ISSUE TITLE
setuptools 44.1.1 is too old and conflicts with new packages

### ISSUE THREAD

**Issue by goduck777** [ankitects/anki#1245]
I am trying to build the package using bazel with python3.9. I believe that one of the python package requires setuptools>=45, but in the current bazel repository setup only setuptools 44.1.1 is provided.

The package was fetched following the rules at

https://github.com/ankitects/rules_pip/tree/master/third_party/py

which is quite behind the upstream. I hope the developer can do an upgrade of the package version.

**Comment by dae** [comment]
What's the error you're getting, and the text around it?

**Comment by goduck777** [comment]
Here is the error message
```
anki-2.1.44 % ./run
Starting local Bazel server and connecting to it...
INFO: Repository pypi__39__pyrsistent_0_17_3 instantiated at:
  /home/xxxxx/Downloads/anki-2.1.44/WORKSPACE:18:16: in <toplevel>
  /home/xxxxx/Downloads/anki-2.1.44/late_deps.bzl:7:16: in setup_late_deps
  /home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/py_deps/requirements.bzl:500:16: in pip_install
Repository rule whl_library defined at:
  /home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/defs.bzl:137:30: in <toplevel>
ERROR: An error occurred during the fetch of repository 'pypi__39__pyrsistent_0_17_3':
   Traceback (most recent call last):
	File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/defs.bzl", line 135, column 13, in _whl_impl
		fail("whl_library failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: whl_library failed: Ignoring atomicwrites: markers 'sys_platform == "win32"' don't match your environment
Ignoring colorama: markers 'sys_platform == "win32"' don't match your environment
Ignoring psutil: markers 'sys_platform == "win32"' don't match your environment
Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
Ignoring winrt: markers 'sys_platform == "win32" and platform_release == "10"' don't match your environment
Collecting pyrsistent==0.17.3
  Using cached pyrsistent-0.17.3.tar.gz (106 kB)
 (    ERROR: Command errored out with exit status 1:
     command: /usr/lib/python-exec/python3.9/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-51ktnkos/pyrsistent/setup.py'"'"'; __file__='"'"'/tmp/pip-install-51ktnkos/pyrsistent/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base /tmp/pip-pip-egg-info-9tngum33
         cwd: /tmp/pip-install-51ktnkos/pyrsistent/
    Complete output (23 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-51ktnkos/pyrsistent/setup.py", line 52, in <module>
        setup(
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.9/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/setuptools/dist.py", line 447, in __init__
        _Distribution.__init__(self, {
      File "/usr/lib/python3.9/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/setuptools/dist.py", line 739, in finalize_options
        for ep in sorted(eps, key=by_order):
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/setuptools/dist.py", line 738, in <lambda>
        eps = map(lambda e: e.load(), pkg_resources.iter_entry_points(group))
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/pkg_resources/__init__.py", line 2442, in load
        self.require(*args, **kwargs)
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/pkg_resources/__init__.py", line 2465, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/pkg_resources/__init__.py", line 791, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (setuptools 44.1.1 (/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py), Requirement.parse('setuptools>=45'))
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Traceback (most recent call last):
  File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/src/whl.py", line 261, in <module>
    main()
  File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/src/whl.py", line 203, in main
    pkg = install_package(args.package, args.directory, pip_args)
  File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/src/whl.py", line 78, in install_package
    dist_info = glob.glob(os.path.join(directory, "*.dist-info"))[0]
IndexError: list index out of range
)
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/defs.bzl", line 135, column 13, in _whl_impl
		fail("whl_library failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: whl_library failed: Ignoring atomicwrites: markers 'sys_platform == "win32"' don't match your environment
Ignoring colorama: markers 'sys_platform == "win32"' don't match your environment
Ignoring psutil: markers 'sys_platform == "win32"' don't match your environment
Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
Ignoring winrt: markers 'sys_platform == "win32" and platform_release == "10"' don't match your environment
Collecting pyrsistent==0.17.3
  Using cached pyrsistent-0.17.3.tar.gz (106 kB)
 (    ERROR: Command errored out with exit status 1:
     command: /usr/lib/python-exec/python3.9/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-51ktnkos/pyrsistent/setup.py'"'"'; __file__='"'"'/tmp/pip-install-51ktnkos/pyrsistent/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base /tmp/pip-pip-egg-info-9tngum33
         cwd: /tmp/pip-install-51ktnkos/pyrsistent/
    Complete output (23 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-51ktnkos/pyrsistent/setup.py", line 52, in <module>
        setup(
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.9/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/setuptools/dist.py", line 447, in __init__
        _Distribution.__init__(self, {
      File "/usr/lib/python3.9/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/setuptools/dist.py", line 739, in finalize_options
        for ep in sorted(eps, key=by_order):
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/setuptools/dist.py", line 738, in <lambda>
        eps = map(lambda e: e.load(), pkg_resources.iter_entry_points(group))
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/pkg_resources/__init__.py", line 2442, in load
        self.require(*args, **kwargs)
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/pkg_resources/__init__.py", line 2465, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/pkg_resources/__init__.py", line 791, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (setuptools 44.1.1 (/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py), Requirement.parse('setuptools>=45'))
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Traceback (most recent call last):
  File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/src/whl.py", line 261, in <module>
    main()
  File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/src/whl.py", line 203, in main
    pkg = install_package(args.package, args.directory, pip_args)
  File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/src/whl.py", line 78, in install_package
    dist_info = glob.glob(os.path.join(directory, "*.dist-info"))[0]
IndexError: list index out of range
)
ERROR: /home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/pypi__39__jsonschema_3_2_0/BUILD:6:11: @pypi__39__jsonschema_3_2_0//:pkg depends on @pypi__39__pyrsistent_0_17_3//:pkg in repository @pypi__39__pyrsistent_0_17_3 which failed to fetch. no such package '@pypi__39__pyrsistent_0_17_3//': whl_library failed: Ignoring atomicwrites: markers 'sys_platform == "win32"' don't match your environment
Ignoring colorama: markers 'sys_platform == "win32"' don't match your environment
Ignoring psutil: markers 'sys_platform == "win32"' don't match your environment
Ignoring pywin32: markers 'sys_platform == "win32"' don't match your environment
Ignoring winrt: markers 'sys_platform == "win32" and platform_release == "10"' don't match your environment
Collecting pyrsistent==0.17.3
  Using cached pyrsistent-0.17.3.tar.gz (106 kB)
 (    ERROR: Command errored out with exit status 1:
     command: /usr/lib/python-exec/python3.9/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-51ktnkos/pyrsistent/setup.py'"'"'; __file__='"'"'/tmp/pip-install-51ktnkos/pyrsistent/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --no-user-cfg egg_info --egg-base /tmp/pip-pip-egg-info-9tngum33
         cwd: /tmp/pip-install-51ktnkos/pyrsistent/
    Complete output (23 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-51ktnkos/pyrsistent/setup.py", line 52, in <module>
        setup(
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/setuptools/__init__.py", line 162, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.9/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/setuptools/dist.py", line 447, in __init__
        _Distribution.__init__(self, {
      File "/usr/lib/python3.9/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/setuptools/dist.py", line 739, in finalize_options
        for ep in sorted(eps, key=by_order):
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/setuptools/dist.py", line 738, in <lambda>
        eps = map(lambda e: e.load(), pkg_resources.iter_entry_points(group))
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/pkg_resources/__init__.py", line 2442, in load
        self.require(*args, **kwargs)
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/pkg_resources/__init__.py", line 2465, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py/pkg_resources/__init__.py", line 791, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (setuptools 44.1.1 (/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/third_party/py), Requirement.parse('setuptools>=45'))
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
Traceback (most recent call last):
  File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/src/whl.py", line 261, in <module>
    main()
  File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/src/whl.py", line 203, in main
    pkg = install_package(args.package, args.directory, pip_args)
  File "/home/xxxxx/.cache/bazel/_bazel_xxxxx/223a0b823e9a86ef4f5c4737fe928aa8/external/com_github_ali5h_rules_pip/src/whl.py", line 78, in install_package
    dist_info = glob.glob(os.path.join(directory, "*.dist-info"))[0]
IndexError: list index out of range
)
ERROR: Analysis of target '//qt:runanki' failed; build aborted: Analysis failed
INFO: Elapsed time: 22.749s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (103 packages loaded, 3986 target\
FAILED: Build did NOT complete successfully (103 packages loaded, 3986 target\
s configured)
    Fetching @pypi__39__six_1_15_0; fetching 17s
    Fetching @pypi__39__certifi_2020_12_5; fetching 17s
    Fetching @rust_linux_x86_64; fetching 17s
    Fetching @pypi__39__black_20_8b1; fetching 17s
    Fetching @pypi__39__click_7_1_2; fetching 17s
    Fetching @pypi__39__urllib3_1_26_3; fetching 17s
    Fetching @pypi__39__stringcase_1_2_0; fetching 16s
    Fetching ...x86_64; Extracting /home/xxxxx/.cache/bazel/_bazel_xxxxx\
g/223a0b823e9a86ef4f5c4737fe928aa8/external/rust_linux_x86_64/rust-1.48.0-x86\
_64-unknown-linux-gnu.tar.gz 6s
```

**Comment by dae** [comment]
Thanks for that, please let me know how you go with the latest HEAD.

**Comment by goduck777** [comment]
The new HEAD version compiles and runs well. Thank you for fixing this!
