### ISSUE TITLE
Can't compile anki head `ImportError: cannot import name 'ensure_text' from 'six'`

### ISSUE THREAD

**Issue by MartinX3** [ankitects/anki#1338]
```
Traceback (most recent call last):
  File "/usr/bin/pip", line 33, in <module>
    sys.exit(load_entry_point('pip==20.3.4', 'console_scripts', 'pip')())
  File "/usr/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 73, in main
    command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/__init__.py", line 105, in create_command
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/pip/_internal/commands/install.py", line 14, in <module>
    from pip._internal.cache import WheelCache
  File "/usr/lib/python3.9/site-packages/pip/_internal/cache.py", line 15, in <module>
    from pip._internal.utils.temp_dir import TempDirectory, tempdir_kinds
  File "/usr/lib/python3.9/site-packages/pip/_internal/utils/temp_dir.py", line 11, in <module>
    from pip._vendor.six import ensure_text
ImportError: cannot import name 'ensure_text' from 'six' (/home/martin/.local/lib/python3.9/site-packages/six.py)
```

My AUR package
https://aur.archlinux.org/packages/anki-git/
The AUR build script
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=anki-git

**Comment by dae** [comment]
Maybe the version of 'six' you have installed is too old or too new.

**Comment by MartinX3** [comment]
It's `1.16.0` if I looked correctly.

**Comment by dae** [comment]
It appears not, as that name is there: 
https://github.com/benjaminp/six/blob/65486e4383f9f411da95937451205d3c7b61b9e1/six.py#L939

I suggest you try build Anki following the instructions in Anki's README, to rule out issues with your distro's package.

**Comment by MartinX3** [comment]
Sadly I follow already the ANKI instructions and use the build script.

**Comment by MartinX3** [comment]
Fixed my removing the folder `~/.local/lib/python3.9/`
Don't ask me why it existed / was broken.
