### ISSUE TITLE
Graphical window margin issues on Ubuntu (i3wm)

### ISSUE THREAD

**Issue by guillaumematheron** [ankitects/anki#1480]
Hi, 

This is my first contribution so please let me know if this is the right place or if I should add this to the Discourse instead.

I have graphical issues with anki (desktop app) on Linux. I use i3wm which I suspect could be the issue.

![Screenshot from 2021-11-07 08-18-31](https://user-images.githubusercontent.com/1949438/140636286-e2f1df1d-8ad4-440b-ad78-842c6f748ea4.png)
![Screenshot from 2021-11-07 08-18-54](https://user-images.githubusercontent.com/1949438/140636288-0e951e84-ce6d-4be1-b325-2d4d4d4b2559.png)

I think this looks like a margin error that could be caused by the graphical environment or WM (i3wm has no title or status bar for instance), scrollbars etc...

As seen in the first screenshot it impedes on functionality because parts of the window contents are overflowing.

Version:
```
$ sha256sum anki-2.1.49-linux.tar.bz2 
b86dfd83d0979eab80ac5b31b451d65a80da370bbccb628a87e4aa1adf1aaa2d  anki-2.1.49-linux.tar.bz2

$ i3 --version
i3 version 4.17.1 (2019-08-30) © 2009 Michael Stapelberg and contributors

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

$ uname -r
5.11.0-38-generic
```

Console output:
```
~/Downloads/anki-2.1.49-linux$ anki 
mpv not found, reverting to mplayer
Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 41, in cmd
  File "aqt/webview.py", line 142, in _onCmd
  File "aqt/webview.py", line 595, in _onBridgeCmd
  File "aqt/deckbrowser.py", line 116, in _linkHandler
  File "aqt/deckbrowser.py", line 374, in _confirm_upgrade
  File "anki/collection.py", line 300, in mod_schema
anki.errors.AbortSchemaModification

Caught exception:
Traceback (most recent call last):
  File "aqt/webview.py", line 41, in cmd
  File "aqt/webview.py", line 142, in _onCmd
  File "aqt/webview.py", line 595, in _onBridgeCmd
  File "aqt/deckbrowser.py", line 116, in _linkHandler
  File "aqt/deckbrowser.py", line 374, in _confirm_upgrade
  File "anki/collection.py", line 300, in mod_schema
anki.errors.AbortSchemaModification

JS error /_anki/pages/congrats.html:1 Uncaught SyntaxError: Identifier 'style' has already been declared
Not found: 'favicon.ico'
```

**Comment by dae** [comment]
Tried changing the video driver in the preferences screen?
