### ISSUE TITLE
ImportError: cannot import name 'Card' from partially initialized module 'anki.cards'

### ISSUE THREAD

**Issue by dmella2** [ankitects/anki#1531]
Hi there,

I am trying to follow this tutorial: https://addon-docs.ankiweb.net/editor-setup.html

I am learnig italian, and I would like to create an addon. 

When, I try to do this:

from anki import hooks

I have this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\Lib\site-packages\anki\hooks.py", line 20, in <module>
    from anki.hooks_gen import *
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\Lib\site-packages\anki\hooks_gen.py", line 14, in <module>
    from anki.cards import Card
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\Lib\site-packages\anki\cards.py", line 15, in <module>
    from anki.consts import *
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\Lib\site-packages\anki\consts.py", line 94, in <module>
    import anki.collection
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\Lib\site-packages\anki\collection.py", line 44, in <module>
    import anki.latex
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\Lib\site-packages\anki\latex.py", line 15, in <module>
    from anki.template import TemplateRenderContext, TemplateRenderOutput
  File "C:\Users\Utente\AppData\Local\Programs\Python\Python39\Lib\site-packages\anki\template.py", line 36, in <module>
    from anki.cards import Card
ImportError: cannot import name 'Card' from partially initialized module 'anki.cards' (most likely due to a circular import) (C:\Users\Utente\AppData\Local\Programs\Python\Python39\Lib\site-packages\anki\cards.py)

I am using: 
Python  3.9.4
Windows 10

Thanks.

**Comment by dmella2** [comment]
Note: I am using the Windows cmd console.

**Comment by dmella2** [comment]
Also doing this:

from anki.cards import Card

I get this error: 

ImportError: cannot import name 'Card' from partially initialized module 'anki.cards' (most likely due to a circular import) (C:\Users\Utente\AppData\Local\Programs\Python\Python39\Lib\site-packages\anki\cards.py)

**Comment by dae** [comment]
From that page:

> Please note that you can not run your add-on from within PyCharm - you will get errors. Add-ons need to be run from within Anki, which is covered in the A Basic Add-on section.

Please post any further questions you have over on the forums.
