### ISSUE TITLE
Use graphs components from other ts folders

### ISSUE THREAD

**Issue by kleinerpirat** [ankitects/anki#2088]
@hgiesel I saw you're online right now. I'm trying to include graphs in a pane on the main window from a new file `ts/main/overview/Stats.svelte`:

```ts
<script lang="ts">
    import { onMount } from "svelte";
    import "../../graphs/graphs-base.css";

    import GraphsPage from "../../graphs/GraphsPage.svelte";

    import CalendarGraph from "../../graphs/CalendarGraph.svelte";
    import CardCounts from "../../graphs/CardCounts.svelte";
    import IntervalsGraph from "../../graphs/IntervalsGraph.svelte";
    import ReviewsGraph from "../../graphs/ReviewsGraph.svelte";

    export let curDeck: string;

    let element: HTMLElement;
    let graphs = [
        ReviewsGraph,
        CalendarGraph,
        CardCounts,
        IntervalsGraph,
    ];

    onMount(async () => {
        new GraphsPage({
            target: element,
            props: {
                initialSearch: `deck:${curDeck}`,
                initialDays: 365,
                controller: null,
                graphs,
            },
        });
    });
</script>

<div bind:this={element} />
```

but I get this error:
```
  errors: [
    {
      detail: undefined,
      location: [Object],
      notes: [],
      pluginName: '',
      text: 'Could not resolve "../../graphs/graphs-base.css"'
    },
   ...
  ]
```

I tried to include `//ts/graphs` in the Bazel file for the main window folder, but it doesn't work. Could you provide a short example of how to use the graph components in other screens?

**Comment by hgiesel** [comment]
First of all, you need to add the graphs directory in both `BUILD.bazel` and `tsconfig.json`. You can look at the other directories for examples.

**Comment by kleinerpirat** [comment]
Thanks, Henrik. I already looked at a lot of directories.. it's what I usually do when I don't know how to proceed. But so far to no avail.

`tsconfig.json`:
```json
{
    "extends": "../tsconfig.json",
    "include": ["*"],
    "references": [
        { "path": "../lib" },
        { "path": "../graphs" },
    ]
}
```
`BUILD.bazel`:
```bazel
compile_svelte(
    deps = ["//ts/lib", "//ts/graphs"],
)

typescript(
    name = "index",
    deps = [
        ":svelte",
        "//ts/components",
        "//ts/lib",
        "//ts/graphs",
        "@npm...",
        ...
    ],
)
```
I get:
```
ERROR: /home/kleinerpirat/Documents/GitHub/anki/ts/main/BUILD.bazel:21:15: in svelte rule //ts/main:svelte: 
Traceback (most recent call last):
        File "/home/kleinerpirat/Documents/GitHub/anki/ts/svelte/svelte.bzl", line 49, column 54, in _svelte
                deps = depset([], transitive = [_get_declarations(dep) for dep in ctx.attr.deps])
        File "/home/kleinerpirat/Documents/GitHub/anki/ts/svelte/svelte.bzl", line 13, column 13, in _get_declarations
                fail("unexpected dep", dep)
Error in fail: unexpected dep <target //ts/graphs:graphs>
```
How would I make the dependency "expected"? :D

**Comment by hgiesel** [comment]
Ah, you need to include the build product of `typescript`, which in graphs is called index, so you need to include `//ts/graphs:index` instead.

**Comment by kleinerpirat** [comment]
Thank you very much, that did the trick! :pray:

**Comment by kleinerpirat** [comment]
Little sneak peek of the WIP:

![image](https://user-images.githubusercontent.com/62722460/192168904-9a771c6f-84c6-42d8-92b7-3f8f4af730c6.png)
