### ISSUE TITLE
start stack

### ISSUE THREAD

**Issue by orangeagain** [ankitects/anki#2192]
on windows 11
```
Anki starting...
Initial setup...
Preparing to run...
webview proxy use disabled
update check failed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading", line 973, in _bootstrap_inner
  File "aqt.mediasrv", line 83, in run
  File "waitress.server", line 78, in create_server
  File "waitress.server", line 229, in __init__
  File "waitress.trigger", line 173, in __init__
TimeoutError: [WinError 10060] 鐢变簬杩炴帴鏂瑰湪涓€娈垫椂闂村悗娌℃湁姝ｇ‘绛斿鎴栬繛鎺ョ殑涓绘満娌℃湁鍙嶅簲锛岃繛鎺ュ皾璇曞け璐ャ€?

Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <MediaServer(Thread-1, started 768)>>
Traceback (most recent call last):
  File "threading", line 930, in _bootstrap
  File "threading", line 975, in _bootstrap_inner
  File "threading", line 1244, in invoke_excepthook
AttributeError: 'ErrorHandler' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'
```

seem network problem? is possible config proxy on anki?

**Comment by orangeagain** [comment]
https://forums.ankiweb.net/t/anki-2-33-will-not-start/2882/8
still on 2.1.54
run:
```
import os
import flask
from waitress.server import create_server

app = flask.Flask(__name__)

desired_port = int(os.getenv("ANKI_API_PORT", "0"))
server = create_server(app, host="127.0.0.1", port=desired_port)

print("Serving on http://%s:%s"% (server.effective_host, server.effective_port))
```
give error:
```
Traceback (most recent call last):
  File "C:\Users\Rika\Desktop\test.py", line 9, in <module>
    server = create_server(app, host="127.0.0.1", port=desired_port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rika\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\waitress\server.py", line 78, in create_server
    last_serv = TcpWSGIServer(
                ^^^^^^^^^^^^^^
  File "C:\Users\Rika\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\waitress\server.py", line 229, in __init__
    self.trigger = trigger.trigger(map)
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Rika\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\waitress\trigger.py", line 171, in __init__
    w.connect(connect_address)
TimeoutError: [WinError 10060]
```

**Comment by orangeagain** [comment]
resolved by close windows firewall, damn
