### ISSUE TITLE
Unable to open browser on windows

### ISSUE THREAD

**Issue by jeremyalexx** [ankitects/anki#2291]
Hi all,

I recently updated to Anki 2.1.55 - in doing so I have been unable to open the browsers on my Windows OS (it works fine on my 
 MacOS).

I have tried disabling the mentioned addons and it does not work but the issue does resolve when Anki is started using safe mode (no addons active), Below is debug information:

Debug info:
Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-12-30 16:36:05

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 43, in cmd
  File "aqt.webview", line 150, in _onCmd
  File "aqt.webview", line 620, in _onBridgeCmd
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "C:\Users\jerem\AppData\Roaming\Anki2\addons21\zkingofstudytimers\__init__.py", line 606, in myLinkHandler
    return _old(self, url)
  File "aqt.toolbar", line 168, in _linkHandler
  File "aqt.toolbar", line 186, in _browseLinkHandler
  File "aqt.main", line 1167, in onBrowse
  File "aqt", line 130, in open
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 80, in repl
  File "aqt.browser.browser", line 135, in __init__
  File "aqt.browser.browser", line 620, in setupSidebar
  File "aqt.browser.sidebar.tree", line 95, in __init__
  File "aqt.browser.sidebar.tree", line 107, in _setup_style
  File "aqt.theme", line 181, in var
TypeError: tuple indices must be integers or slices, not str

Kind regards,
JA
![image](https://user-images.githubusercontent.com/68852840/210041352-66bb9090-01c5-47c0-b344-c01fdb055d67.png)

**Comment by dae** [comment]
What error do you get when you start Anki while holding down shift?

**Comment by jeremyalexx** [comment]
Hey Damien, no error. It starts and works normally if shift is held.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dae** [comment]
Then that tells us the issue is caused by an add-on, likely "zkingofstudytimers". Please let the add-on author know.

**Comment by jeremyalexx** [comment]
Hi Damien, disabling that Addon does not provide a resolution, I’ve already tried.

I’ll raise it with them anyway.  Thank you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dae** [comment]
Did you make sure to restart Anki after disabling it to confirm?

**Comment by jeremyalexx** [comment]
Sure did. That’s why I raised this ticket. I’ll raise it with the developers nonetheless.

Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dae** [comment]
To isolate the issue, you'll need to disable a few add-ons, restart, and see if the problem goes away, repeating until you figure out which add-on or combination of them causes the issue to occur.

**Comment by jeremyalexx** [comment]
Morning Damien,

 

This is the issue which occurs after I remove and/or suspend the zkingofstudytimers addon.

 

Error 

An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 

If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 

When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 

Debug info:

Anki 2.1.55 (01caec2a) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5

Platform: Windows-10-10.0.22621

Flags: frz=True ao=True sv=2

Add-ons, last update check: 2022-12-30 16:36:05

 

Caught exception:

Traceback (most recent call last):

  File "aqt.webview", line 43, in cmd

  File "aqt.webview", line 150, in _onCmd

  File "aqt.webview", line 620, in _onBridgeCmd

  File "aqt.toolbar", line 168, in _linkHandler

  File "aqt.toolbar", line 186, in _browseLinkHandler

  File "aqt.main", line 1167, in onBrowse

  File "aqt", line 130, in open

  File "decorator", line 232, in fun

  File "anki.hooks", line 89, in decorator_wrapper

  File "anki.hooks", line 80, in repl

  File "aqt.browser.browser", line 135, in __init__

  File "aqt.browser.browser", line 620, in setupSidebar

  File "aqt.browser.sidebar.tree", line 95, in __init__

  File "aqt.browser.sidebar.tree", line 107, in _setup_style

  File "aqt.theme", line 181, in var

TypeError: tuple indices must be integers or slices, not str

 

Kind regards,

Alex Loughlin

**Comment by dae** [comment]
Does the issue go away if you disable all add-ons and then restart? If so, that implies one of your add-ons is causing it.
