### ISSUE TITLE
No module named 'ankirspy'

### ISSUE THREAD

**Issue by kostabekre** [ankitects/anki#2400]
I tried to install anki as sync server without GUI dependencies using termux 
python version: 3.11.2
error:
`Traceback (most recent call last):`
 `File "<frozen runpy>", line 189, in _run_module_as_main`
` File "<frozen runpy>", line 112, in _get_module_details`
 `File "/data/data/com.termux/files/home/syncserver/lib/python3.11/site-packages/anki/__init__.py", line 7, in <module>
    from anki.storage import Collection`
`File "/data/data/com.termux/files/home/syncserver/lib/python3.11/site-packages/anki/storage.py", line 11, in <module>
    from anki.collection import _Collection`
 `File "/data/data/com.termux/files/home/syncserver/lib/python3.11/site-packages/anki/collection.py", line 19, in <module>
    import anki.find`
`File "/data/data/com.termux/files/home/syncserver/lib/python3.11/site-packages/anki/find.py", line 9, in <module>
    from anki.hooks import *`
 `File "/data/data/com.termux/files/home/syncserver/lib/python3.11/site-packages/anki/hooks.py", line 20, in <module>
  from anki.cards import Card`
 `File "/data/data/com.termux/files/home/syncserver/lib/python3.11/site-packages/anki/cards.py", line 15, in <module>
 from anki.rsbackend import BackendCard`
` File "/data/data/com.termux/files/home/syncserver/lib/python3.11/site-packages/anki/rsbackend.py", line 32, in <module>`
` import ankirspy  # pytype: disable=import-error`
`^^^^^^^^^^^^^^^`
`ModuleNotFoundError: No module named 'ankirspy'`

I did:
`python3 -m venv ~/syncserver`
`~/syncserver/bin/pip install anki`
Error when adding a user:
`SYNC_USER1=user:pass ~/syncserver/bin/python -m anki.syncserver`

I searched for the package but the latest version is ankirspy 2.1.35 which is coded for cp38 but in the doc written:
> You can run the server without installing the GUI portion of Anki provided you have a copy of Python3.9+ installed.

**Comment by kostabekre** [comment]
Found the reason: installed anki version was 2.1.25.
I think the reason for that is termux has pip version of 22.3.1
but you can update pip because when I wrote `python3 -m pip install --upgrade pip`, I got the error:
`ERROR: Installing pip is forbidden, this will break the python-pip package (termux).`

I updated the pip inside the created environment: 
`~/syncserver/bin/pip install --upgrade pip`

Also i upgrated setuptools
`~/syncserver/bin/pip install setuptools --upgrade`

still I can only install older versions:
`ERROR: Could not find a version that satisfies the requirement anki==2.1.60 (from versions: 2.1.24+359b9f5c, 2.1.25, 2.1.26, 2.1.28, 2.1.29, 2.1.30, 2.1.31, 2.1.32, 2.1.33, 2.1.34, 2.1.35)
ERROR: No matching distribution found for anki==2.1.60`

**Comment by kostabekre** [comment]
tried to install .whl files got
`ERROR: anki-2.1.60-cp39-abi3-manylinux_2_28_x86_64.whl is not a supported wheel on this platform.`
New versions of anki are not supported for termux
