### ISSUE TITLE
getting this error message while starting  anki

### ISSUE THREAD

**Issue by Abhishekcmd** [ankitects/anki#2737]
- Have a question or feature suggestion?
- Problems building/running on your system?
- Not 100% sure you've found a bug?

If so, please post on https://forums.ankiweb.net/ instead. This issue tracker is
intended primarily to track development tasks, and it is easier to provide support
over on the forums. Please make sure you read the following pages before
you post there:

- https://faqs.ankiweb.net/when-problems-occur.html
- https://faqs.ankiweb.net/getting-help.html

If you post questions, suggestions, or vague bug reports here, please do not be
offended if we close your ticket without replying. If in doubt, please post on
https://forums.ankiweb.net/ instead.

**Comment by Abhishekcmd** [comment]
Error
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨385888438⁩':
⁨Traceback (most recent call last):
  File "aqt.addons", line 246, in loadAddons
  File "C:\Users\joyst\AppData\Roaming\Anki2\addons21\385888438\__init__.py", line 3, in <module>
    from . import firstrun
  File "C:\Users\joyst\AppData\Roaming\Anki2\addons21\385888438\firstrun.py", line 141, in <module>
    version_string = meta["human_version"]
KeyError: 'human_version'
⁩
