### ISSUE TITLE
Fails to start on Windows

### ISSUE THREAD

**Issue by dae** [ankitects/anki#2973]
A small number of users appear to have trouble starting Anki on Windows. When running from anki-console.bat, Anki appears to exit immediately after starting the main loop:
```
[...]
Starting main loop...
Press any key to continue . . .
```

This is presumably a bug in Qt.

One user reported the problem disappeared when they stopped using external monitors:

https://forums.ankiweb.net/t/anki-wont-start-up-at-all/35243/8

Another reported that a reboot helped:

https://forums.ankiweb.net/t/anki-wont-open-on-my-desktop/23225

**Comment by dae** [comment]
If none of those help, you could try installing Qt, and running a webengine example app. If it fails to run, please report the issue to Qt. If it runs correctly, that implies it's an issue with Anki's integration and not Qt itself.

https://github.com/ankitects/anki/issues/2652

**Comment by Pineapplenuts** [comment]
I have this same issue on the latest 24.04 beta but on linux qt 6 variant.  This is the output after I ran `anki` after the install script finished running.

`Anki starting...
Initial setup...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "aqt", line 48, in <module>
  File "anki.lang", line 12, in <module>
  File "anki._backend", line 50, in <module>
Exception: rsbridge and anki build hashes do not match:
4fc535ec vs bfaa28fe
`

**Comment by dae** [comment]
For the people using a beta version, please see the beta thread. https://forums.ankiweb.net/t/anki-24-04-beta/41792/4
