### ISSUE TITLE
Image Occlusion Error

### ISSUE THREAD

**Issue by xip0enix** [ankitects/anki#3509]
Hi there,
I wanted to upload an image to Image Occlusion, but it didn't work…

Here is the error message I received:
Anki 24.10 (eae9bbc4)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631

Traceback (most recent call last):
  File "aqt.webview", line 53, in cmd
  File "aqt.webview", line 163, in _onCmd
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1374772155\editor.py", line 94, in _onBridgeCmd
    self._maybeRunActions()
  File "C:\Users\...\AppData\Roaming\Anki2\addons21\1374772155\editor.py", line 104, in _maybeRunActions
    name, args = self._pendingActions.pop(0)
TypeError: cannot unpack non-iterable function object

Error in sys.excepthook:
Traceback (most recent call last):

Original exception was:
Traceback (most recent call last):

===Add-ons (active)===
Image Occlusion Enhanced ['1374772155', 2022-04-09T09:15, 'None', '']

**Comment by DerIshmaelite** [comment]
https://github.com/ankitects/anki/pull/3475#issuecomment-2408615750
