### ISSUE TITLE
FSRS Simulator Failure: min > max, or either was NaN, in one of my decks

### ISSUE THREAD

**Issue by OuOu2021** [ankitects/anki#3638]
## Description:
When I attempted to use the FSRS simulator on a specific deck, the process failed. The affected deck triggered an error when calling `/simulateFsrsReview`. It then caused an infinite repetition of the `aqt.mediasrv: POST /_anki/latestProgress` until I close the deck-option window. The program did not crash at this point, however, until I tried another operation like reviewing a deck. This issue appears to be isolated to one of my decks, as others work correctly without any issues. 

I'm sure the issue is introduced in PR https://github.com/ankitects/anki/pull/3628.

## Log Details:
```text
2024-12-14 23:01:40,878:DEBUG:aqt.mediasrv: POST /_anki/getDeckConfigsForUpdate
2024-12-14 23:01:57,373:DEBUG:aqt.mediasrv: POST /_anki/simulateFsrsReview
thread '<unnamed>' panicked at /rustc/f6e511eec7342f59a25f7c0534f1dbea00d01b14\library\core\src\num\f32.rs:1433:9:
min > max, or either was NaN. min = 0.01, max = 0.009209633
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-12-14 23:01:57,463:ERROR:waitress: Exception when servicing <waitress.channel.HTTPChannel connected 127.0.0.1:8267 at 0x2426219d190>
Traceback (most recent call last):
  File "C:\Users\11131\Documents\GitHub\anki\out\pyenv\lib\site-packages\waitress\task.py", line 84, in handler_thread
    task.service()
  File "C:\Users\11131\Documents\GitHub\anki\out\pyenv\lib\site-packages\waitress\channel.py", line 430, in service
    task.service()
  File "C:\Users\11131\Documents\GitHub\anki\out\pyenv\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "C:\Users\11131\Documents\GitHub\anki\out\pyenv\lib\site-packages\waitress\task.py", line 436, in execute
    app_iter = self.channel.server.application(environ, start_response)
  File "C:\Users\11131\Documents\GitHub\anki\out\pyenv\lib\site-packages\waitress\proxy_headers.py", line 64, in translate_proxy_headers
    return app(environ, start_response)
  File "C:\Users\11131\Documents\GitHub\anki\out\pyenv\lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\11131\Documents\GitHub\anki\out\pyenv\lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\11131\Documents\GitHub\anki\out\pyenv\lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\11131\Documents\GitHub\anki\out\pyenv\lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "C:\Users\11131\Documents\GitHub\anki\qt\aqt\mediasrv.py", line 313, in handle_request
    return _handle_dynamic_request(req)
  File "C:\Users\11131\Documents\GitHub\anki\qt\aqt\mediasrv.py", line 716, in _handle_dynamic_request
    return req()
  File "C:\Users\11131\Documents\GitHub\anki\qt\aqt\mediasrv.py", line 658, in wrapped
    if data := handler():
  File "C:\Users\11131\Documents\GitHub\anki\qt\aqt\mediasrv.py", line 639, in <lambda>
    return lambda: getattr(aqt.mw.col._backend, f"{endpoint}_raw")(request.data)
  File "C:\Users\11131\Documents\GitHub\anki\out/pylib\anki\_backend_generated.py", line 996, in simulate_fsrs_review_raw
    return self._run_command(11, 32, message)
  File "C:\Users\11131\Documents\GitHub\anki\pylib\anki\_backend.py", line 161, in _run_command
    return self._backend.command(service, method, input)
pyo3_runtime.PanicException: min > max, or either was NaN. min = 0.01, max = 0.009209633
2024-12-14 23:01:57,474:DEBUG:aqt.mediasrv: POST /_anki/latestProgress
2024-12-14 23:01:57,587:DEBUG:aqt.mediasrv: POST /_anki/latestProgress

......(infinite repetition of the `POST /_anki/latestProgress` until I close the deck-option window)

thread '<unnamed>' panicked at rslib\src\backend\mod.rs:122:18:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
Traceback (most recent call last):
  File "C:\Users\11131\Documents\GitHub\anki\qt\aqt\deckbrowser.py", line 316, in <lambda>
    qconnect(a.triggered, lambda b, did=did: self._options(DeckId(int(did))))
  File "C:\Users\11131\Documents\GitHub\anki\qt\aqt\deckbrowser.py", line 344, in _options
    display_options_for_deck_id(did)
  File "C:\Users\11131\Documents\GitHub\anki\qt\aqt\deckoptions.py", line 150, in display_options_for_deck_id
    deck = aqt.mw.col.decks.get(deck_id)
  File "C:\Users\11131\Documents\GitHub\anki\pylib\anki\decks.py", line 247, in get
    deck = self.get_legacy(id)
  File "C:\Users\11131\Documents\GitHub\anki\pylib\anki\decks.py", line 156, in get_legacy
    return from_json_bytes(self.col._backend.get_deck_legacy(did))
  File "C:\Users\11131\Documents\GitHub\anki\out/pylib\anki\_backend_generated.py", line 446, in get_deck_legacy
    raw_bytes = self._run_command(7, 12, message.SerializeToString())
  File "C:\Users\11131\Documents\GitHub\anki\pylib\anki\_backend.py", line 161, in _run_command
    return self._backend.command(service, method, input)
pyo3_runtime.PanicException: called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

-----------
### Debug info:
```text
Anki 24.11 (558aade8) (src) (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.22631-SP0

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AnkiConnect ['2055492159', 2024-11-07T09:34, 'None', mod]
Button Colours Good Again ['2494384865', 2022-09-27T18:18, 'None', '']
Hint Hotkeys ['1844908621', 2023-04-14T22:13, 'None', mod]
History Visualizer ['1545338943', 2024-11-16T23:17, 'None', '']
Minimize to tray ['85158043', 2023-11-27T03:18, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T09:43, 'None', '']
See Previous Card Ratings in Reviewer ['1906641654', 2021-08-20T05:32, 'None', mod]
Speed Focus Mode auto-alert auto-reveal auto-answer ['1046608507', 2022-12-16T19:24, 'None', '']

===IDs of active AnkiWeb add-ons===
1046608507 1545338943 1771074083 1844908621 1906641654 2055492159 2494384865 85158043

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
Advanced Browser ['874215009', 2024-10-27T22:20, 'None', '']
Kanji Grid Kuuube ['1610304449', 2024-11-20T11:11, 'None', '']
Toggle front and back card in Anki 21 ['1240106570', 2019-07-21T21:19, 'None', '']
```

### Problematic deck with learning progress & deck presets
[issue_3638_debug.zip](https://github.com/user-attachments/files/18141389/issue_3638_debug.zip)

**Comment by abdnh** [comment]
It's probably coming from the .clamp() call here: https://github.com/open-spaced-repetition/fsrs-rs/pull/257/files#diff-5457c054860a363cd71c7491b15f7d9b21a29b44dd469c0014883de9f113e412

**Comment by OuOu2021** [comment]
After more testing, I think the error is not entirely due to the deck, but is also related to simulator options. When "Maximum reviews/day" is set to 200, the simulation is successful, but when it is changed to 205, it is stuck in processing.
![Image](https://github.com/user-attachments/assets/e06aaaf8-00c6-4446-b63c-7d8f5c0c6fc0)

**Comment by abdnh** [comment]
@OuOu2021 a sample deck will be helpful for debugging

**Comment by abdnh** [comment]
I can reproduce it. @L-M-Sherlock

**Comment by L-M-Sherlock** [comment]
Thanks, I located the bug. I forgot to clamp `new_s_min` at first.
